### ISSUE TITLE
Untranslated item under Subscriber Counts

### ISSUE THREAD

**Issue by j-norwood-young** [remp2020/crm-subscriptions-module#1]
<img width="310" alt="Screen Shot 2019-06-04 at 11 14 31" src="https://user-images.githubusercontent.com/387601/58867044-0b1d0100-86ba-11e9-8711-ea1cc7f0ab10.png">
"Aktívni predplatelia" (and associated help popup) in Slovakian.

**Comment by markoph** [comment]
Thank you for reporting this. Will be fixed in next release.

**Comment by rootpd** [comment]
Should be fixed since `0.3.2`, closing.
